sudo: true
language: go
services:
  - docker
matrix:
  include:
  - go: 1.11.1
script:
- go fmt $(go list ./... | grep -v vendor) | wc -l | grep 0
- go vet $(go list ./... | grep -v vendor)
- go test $(go list ./... | grep -v vendor)
# for example
# after_success:
#  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
#      docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" quay.io;
#      make push;
#    fi